name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          config_timezone: America/Chicago

          base: header, activity, repositories

          plugin_activity: yes
          plugin_activity_limit: 1
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          plugin_activity_skipped: johngillen

          plugin_achievements: yes
          plugin_achievements_display: compact

          plugin_code: yes
          plugin_code_visibility: public
          plugin_code_languages: python

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_mode: recent
          plugin_music_limit: 1
          plugin_music_played_at: yes

